Enhance Survey README.md
odk-x/survey pull request #172
Opened 2023-10-08 00:57 UTC by permission-error

Fixes partly https://github.com/odk-x/tool-suite-X/issues/431

This PR is still open to suggestions and modifications 

Cc @elmps2018 @wbrunette @Redeem-Grimm-Satoshi @Cveman1

2023-10-08 19:59 UTC, elmps2018 reviewed
@permission-error thanks for working on this! So I am not sure if it makes sense to put here all this information/links to what is in the docs, as this creates some duplication. I think the goal of the readme is about the ODK-X Survey code base, not using ODK-X survey on a tablet or designing a form. @wbrunette what do you think, does this added content belong in the ReadMe or stay in docs?

2023-10-11 17:40 UTC, elmps2018 commented
Hi @permission-error, I am having a hard time comparing to the original since you added a whole lot and then took it out, can you close this and try to push again against what was originally there to make it easier to review? Thanks!

2023-10-12 07:51 UTC, permission-error commented
@elmps2018 I just removed most of the content since in the call we discussed most of contents should be in the docs. I just left the TOC and the FAQs

2023-10-12 13:48 UTC, wbrunette requested changes
As discussed on the call, the README should target people developing code. The FAQs added are quite generic and general questions. Unless the FAQ relates to "code" or "development setup" they should be in the documentation not README.

2023-10-13 13:27 UTC, wbrunette commented on README.md
> +It operates similarly to ODK Collect, but is based on HTML, CSS, and Javascript rather than native Android, and is more flexible in its presentation and execution
We were trying to remove all references to ODK in the readme to help with the ODK-X/ODK confusion when people search online. Therefore, I think it's best not to do the comparison in the readme.

2023-10-16 18:04 UTC, elmps2018 commented on README.md
> +Note: Detailed information on how to use the survey can be found [here](https://docs.odk-x.org/survey-using/).
better to say "how to use ODK-X survey" - it's not just one "the survey"

2023-10-16 23:55 UTC, elmps2018 approved these changes
This looks good to me, @wbrunette any comments?

2023-10-17 01:13 UTC, wbrunette approved these changes

2023-10-17 01:13 UTC, merged